# Generated by Django 2.0.1 on 2018-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180206_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_time',
            field=models.DateTimeField(default=None),
        ),
    ]
